dataset:
  data_percent: 100
  #sets_dir: "/data/waymo/ImageSets_samanti" # server
  sets_dir: "/media/samanti/9137dc79-aec9-43a3-8017-08ed5130ad58/home/samanti/waymo/ImageSets_samanti" # PC

bev:
  x_size: 1024
  y_size: 1024
  voxel_size: 0.1
  bev_padding: 3.7
  z_min: -1
  z_max: 2

sensors:
  scala:
    positions:
      # Existing SCALA Gen1 configuration

    common:
      distance: 80
      horizontal_angle_min: -72.5
      horizontal_angle_max: 72.5
      horizontal_rays: 580
      horizontal_increment: 0.25
      vertical_angles: [-0.4, 0.4, 1.2]
      mirror_mode: alternating # possible options: up, down, alternating, both

  scala2:
    positions:
      - name: front_left
        start_point: [3.850, 0.800, 0.743]
        rotation_angle_x: 0.005826
        rotation_angle_y: -0.016451
        rotation_angle_z: 0.333756
        rotation_angle_w: 0.942498

      - name: front_center
        start_point: [4.105, 0.000, 0.625]
        rotation_angle_x: 0.000000
        rotation_angle_y: 0.006981
        rotation_angle_z: 0.000000
        rotation_angle_w: 0.999976

      - name: front_right
        start_point: [3.860, -0.810, 0.740]
        rotation_angle_x: 0.000000
        rotation_angle_y: 0.000000
        rotation_angle_z: -0.358368
        rotation_angle_w: 0.933580

      - name: rear_left
        start_point: [-0.675, 0.985, 0.740]
        rotation_angle_x: 0.000000
        rotation_angle_y: 0.000000
        rotation_angle_z: 0.7071068
        rotation_angle_w: 0.7071068

      - name: rear_center
        start_point: [-1.065, 0.000, 0.350]
        rotation_angle_x: -0.017450
        rotation_angle_y: 0.000260
        rotation_angle_z: 0.999800
        rotation_angle_w: 0.000110

      - name: rear_right
        start_point: [-0.680, -0.982, 0.741]
        rotation_angle_x: 0.000000
        rotation_angle_y: 0.000000
        rotation_angle_z: -0.7325429
        rotation_angle_w: 0.6807209

    common:
      distance: 100.0

      # Horizontal scan pattern
      horizontal_angle_min: -66.5
      horizontal_angle_max: 66.5

      inner_angle_min: -15.0
      inner_angle_max: 15.0

      horizontal_increment_inner: 0.125
      horizontal_increment_outer: 0.25

      # Azimuth staggering between successive APD groups
      apd_group_azimuth_offset: 0.0181
      apd_group_azimuth_sign: 1.0

      # Point placement after Bresenham selects the source point
      # Options: same_distance, orthogonal
      projection_method: orthogonal